export const traditionalProfiles: Profile[] = [
  { code: "271 (a)", weight: "0,54", txp: "4", description: "Marco para Puerta de Rebatir - L├¡nea Recta, sin Contravidrio", page: "0", shape: 'generic' },
  { code: "272", weight: "1,05", txp: "3", description: "Travesa├▒o para Puerta de Rebatir - L├¡nea Recta, sin Contravidrio", page: "0", shape: 'generic' },
  { code: "273 (a)", weight: "0,96", txp: "3", description: "Parante para Puerta de Rebatir - L├¡nea Recta, sin Contravidrio", page: "0", shape: 'generic' },
  { code: "275 (a)", weight: "0,29", txp: "8", description: "Batiente para Puerta de Rebatir - L├¡nea Recta, sin Contravidrio", page: "0", shape: 'generic' },
  { code: "289 (a)", weight: "0,59", txp: "4", description: "Marco Postig├│n", page: "0", shape: 'generic' },
  { code: "290", weight: "0,44", txp: "8", description: "Hoja de Raja", page: "15", shape: 'hoja' },
  { code: "291", weight: "0,35", txp: "12", description: "Marco Postig├│n", page: "0", shape: 'generic' },
  { code: "427 (a)", weight: "0,58", txp: "6", description: "Marco para Puerta de Rebatir - L├¡nea Tradicional", page: "0", shape: 'generic' },
  { code: "428 (a)", weight: "0,98", txp: "3", description: "Parante para Puerta de Rebatir - L├¡nea Tradicional", page: "0", shape: 'generic' },
  { code: "429", weight: "1,01", txp: "3", description: "Travesa├▒o para Puerta de Rebatir - L├¡nea Tradicional", page: "0", shape: 'generic' },
  { code: "432 (a)", weight: "0,79", txp: "6", description: "Marco para Puerta de Rebatir - L├¡nea con Bisagra de Encolizar", page: "0", shape: 'generic' },
  { code: "433 (a)", weight: "1,13", txp: "3", description: "Parante para Puerta de Rebatir - L├¡nea con Bisagra de Encolizar", page: "0", shape: 'generic' },
  { code: "448", weight: "0,3", txp: "10", description: "Tablilla de Postig├│n", page: "0", shape: 'generic' },
  { code: "449", weight: "0,26", txp: "10", description: "Tablilla de Postig├│n Recta", page: "0", shape: 'generic' },
  { code: "453", weight: "0,45", txp: "8", description: "Acople", page: "25", shape: 'acople' },
  { code: "455", weight: "1,18", txp: "2", description: "Columna a 90┬░ / 180┬░", page: "25", shape: 'parante' },
  { code: "462", weight: "0,45", txp: "8", description: "Parante de Postig├│n", page: "0", shape: 'generic' },
  { code: "463 (a)", weight: "0,56", txp: "4", description: "Parante de Postig├│n y Puerta de Rebatir de 24,5 mm.", page: "0", shape: 'generic' },
  { code: "470", weight: "0,27", txp: "8", description: "Perimetral de Vidrio Repartido", page: "14", shape: 'tubo' },
  { code: "471", weight: "0,32", txp: "8", description: "Central de Vidrio Repartido", page: "14", shape: 'tubo' },
  { code: "480", weight: "0,58", txp: "6", description: "Parante Central para Ventana y Puerta Corrediza - L├¡nea Combinada", page: "0", shape: 'generic' },
  { code: "481", weight: "0,68", txp: "4", description: "Hoja para Ventana y Puerta Corrediza - L├¡nea Combinada", page: "0", shape: 'generic' },
  { code: "514 (a)", weight: "0,91", txp: "3", description: "Hoja para Puerta de Rebatir", page: "14", shape: 'hoja' },
  { code: "516 (a)", weight: "0,76", txp: "2", description: "Marco para Ventana Banderola, Ventana y Puerta de Rebatir y Oscilo-Batiente", page: "14", shape: 'marco' },
  { code: "518", weight: "1,0", txp: "4", description: "Refuerzo de Parante", page: "6", shape: 'parante' },
  { code: "552", weight: "0,86", txp: "3", description: "Travesa├▒o de Hoja s/contravidrio", page: "0", shape: 'generic' },
  { code: "553", weight: "0,21", txp: "16", description: "Adaptador para D.V.H.", page: "25", shape: 'acople' },
  { code: "648 (a)", weight: "0,5", txp: "5", description: "Premarco de 55 mm", page: "23", shape: 'premarco' },
  { code: "673", weight: "0,39", txp: "6", description: "Marco para Pa├▒o Fijo de 31,5 mm.", page: "0", shape: 'generic' },
  { code: "702", weight: "0,81", txp: "4", description: "Inversor de Hoja.", page: "14", shape: 'acople' },
  { code: "709 (a)", weight: "0,19", txp: "12", description: "Contramarco Curvo de 30 mm.", page: "24", shape: 'contramarco' },
  { code: "715 (a)", weight: "0,7", txp: "4", description: "Premarco de 77 mm", page: "23", shape: 'premarco' },
  { code: "723 (a)", weight: "0,26", txp: "8", description: "Contramarco Curvo de 45 mm.", page: "24", shape: 'contramarco' },
  { code: "746 (a)", weight: "0,18", txp: "12", description: "Contramarco Curvo de 33 mm.", page: "24", shape: 'contramarco' },
  { code: "901", weight: "0,75", txp: "6", description: "Marco para Ventana y Puerta Corrediza - L├¡nea 900", page: "0", shape: 'generic' },
  { code: "902", weight: "0,4", txp: "8", description: "Z├│calo para Ventana Corrediza", page: "0", shape: 'generic' },
  { code: "907", weight: "0,59", txp: "6", description: "Marco para Pa├▒o Fijo", page: "0", shape: 'generic' },
  { code: "908", weight: "0,16", txp: "20", description: "Contravidrio", page: "18, 19, 20", shape: 'contravidrio' },
  { code: "909", weight: "0,16", txp: "20", description: "Contravidrio", page: "18, 19, 20", shape: 'contravidrio' },
  { code: "915", weight: "0,33", txp: "10", description: "Bisagra para Ventana Ventiluz y Banderola", page: "17, 18", shape: 'bisagra' },
  { code: "916", weight: "0,74", txp: "4", description: "Marco para Ventana Ventiluz y Banderola", page: "17, 18", shape: 'marco' },
  { code: "917", weight: "1,03", txp: "4", description: "Marco para Ventana y Puerta Corrediza - L├¡nea 900 y L├¡nea Tradicional", page: "0", shape: 'generic' },
  { code: "918", weight: "0,51", txp: "8", description: "Hoja para Ventana Ventiluz", page: "17", shape: 'hoja' },
  { code: "919", weight: "0,53", txp: "8", description: "Hoja para Ventana Banderola", page: "18", shape: 'hoja' },
  { code: "921", weight: "1,0", txp: "4", description: "Marco Reforzado para Ventana y Puerta Corrediza - L├¡nea Tradicional", page: "0", shape: 'generic' },
  { code: "952", weight: "0,28", txp: "8", description: "Porta - Contravidrio", page: "20", shape: 'contravidrio' },
  { code: "961", weight: "1,16", txp: "2", description: "Marco de 3 Gu├¡a para Ventana Corrediza", page: "0", shape: 'generic' },
  { code: "986", weight: "1,06", txp: "2", description: "Columna Curva a 90┬░", page: "25", shape: 'parante' },
  { code: "993", weight: "0,67", txp: "8", description: "Travesa├▒o Angosto para Pa├▒o Fijo", page: "0", shape: 'generic' },
  { code: "994", weight: "0,96", txp: "3", description: "Travesa├▒o Ancho para Pa├▒o Fijo", page: "0", shape: 'generic' },
];